blank_issues_enabled: true
contact_links:
  - name: ðŸ’¡ Feature Request
    url: https://github.com/mallory-scotton/moon/discussions/categories/feature-requests
    about: ðŸ’¡ Suggest a new feature, improve an existing feature and etc
  - name: ðŸ¤” Long question or ideas?
    url: https://github.com/mallory-scotton/moon/discussions
    about: Ask long-form questions and discuss ideas.
